name: 'blockwatch linter'
description: 'Runs the blockwatch linter to analyze diffs'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # ensures that git diff is available for previous commits
    # Make the "main" branch available.
    # See https://dev.to/martinratinaud/checkout-several-branches-in-github-actions-3nmc
    - run: git branch main remotes/origin/main
      shell: bash

    - name: Install blockwatch
      run: |
        cargo install blockwatch
      shell: bash

    - name: Run blockwatch
      run: |
        git diff --patch origin/${{ github.base_ref }}...${{ github.sha }} | blockwatch
      shell: bash
