# The test fixtures break the rules on purpose.
ignore = ['tests/testdata/**']

# This block runs on a schedule in .github/workflows/trusted-checks.yml as it needs network access and ideally should
# be avoided in a precommit hook.
skip-blocks = ['src/validators/check_ai.rs:latest-model']
