[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0-prerelease.5"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# A GitHub repo to push Homebrew formulas to
tap = "mennanov/homebrew-blockwatch"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]

[dist.github-custom-runners]
global = "ubuntu-latest"

[dist.github-custom-runners.aarch64-apple-darwin]
runner = "macos-14"

[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-latest"

[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-latest"
