name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: llvm-tools-preview
    - name: Build
      run: cargo build --verbose
      env:
        RUSTFLAGS: '-Cinstrument-coverage'
    - name: Run Clippy lint
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
      env:
        LLVM_PROFILE_FILE: 'blockwatch-%p-%m:profraw'
    - name: Install grcov
      run: |
        mkdir -p "${HOME}/.local/bin"
        curl -sL https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf - -C "${HOME}/.local/bin"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Run grcov
      run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
       files: ./lcov.info
       token: ${{ secrets.CODECOV_TOKEN }}
       verbose: true
       fail_ci_if_error: true
